# Generated by Django 5.2.6 on 2025-09-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=300, verbose_name='Product Name')),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('lgd_code', models.BigIntegerField(verbose_name='LGD Code')),
                ('category', models.CharField(max_length=150)),
                ('sector', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('gi_status', models.CharField(max_length=100, verbose_name='GI Status')),
                ('photo', models.URLField(blank=True, null=True)),
                ('ministry_department', models.CharField(max_length=300, verbose_name='Ministry/Department')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['state', 'district', 'product'],
                'indexes': [models.Index(fields=['state'], name='products_pr_state_f66969_idx'), models.Index(fields=['district'], name='products_pr_distric_833b7f_idx'), models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'), models.Index(fields=['sector'], name='products_pr_sector_e5be0b_idx'), models.Index(fields=['gi_status'], name='products_pr_gi_stat_37939d_idx')],
            },
        ),
    ]
